#!/bin/bash

USER="${USER:-${USERNAME:-aubbwc}}"
qstat -u $USER | grep " Q " > kill.que.txt

JOBS2KILL=$(qstat -u $USER | grep " Q " | cut -d. -f1)

for JOB in $JOBS2KILL ; do
	qdel $JOB && echo $JOB killed.
done

echo script $0 done.

exit 0


