#!/usr/bin/env bash

# sane bash behavior
set -e
set -u

HOSTD_BIN="${HOSTD_BIN:-$HOME/usr/bin}"
HOSTD_LIB="${HOSTD_LIB:-$HOME/usr/lib/hostd}"
files=( ${HOSTD_BIN}/hostd3 ${HOSTD_LIB}/LIBRARY ${HOSTD_LIB}/CONSTANTS ${HOSTD_LIB}/add.prm)

for file in ${files[@]}
do
	cp $file .
done


# copy necessary files here

[[ -e control ]] || ( echo "no control file" && exit 1 )

export HD_DIR='.'
./hostd3 

# remove copied files
for file in ${files[@]}
do
	rm ${file//*\/}
done


